# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_cover_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='data',
            new_name='date',
        ),
    ]
