# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20160326_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('class', '\u0417\u0430\u043d\u044f\u0442\u0438\u044f'), ('fun', '\u0414\u043e\u0441\u0443\u0433'), ('pro', '\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u0438\u0441\u0442\u0430\u043c')], default='class', max_length=10, verbose_name='\u0422\u0438\u043f \u043c\u0435\u0440\u043e\u043f\u0440\u0438\u044f\u0442\u0438\u044f'),
        ),
    ]
