# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.CharField(max_length=255, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
    ]
