# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_follower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'verbose_name': '\u041f\u043e\u0434\u043f\u0438\u0441\u0447\u0438\u043a', 'verbose_name_plural': '\u041f\u043e\u0434\u043f\u0438\u0441\u0447\u0438\u043a\u0438'},
        ),
    ]
