# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expert',
            options={'verbose_name': '\u044d\u043a\u0441\u043f\u0435\u0440\u0442', 'verbose_name_plural': '\u044d\u043a\u0441\u043f\u0435\u0440\u0442\u044b'},
        ),
    ]
