# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f',
                'verbose_name_plural': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='LegotekaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('code', models.CharField(blank=True, max_length=255, verbose_name='\u041a\u043e\u0434')),
                ('available', models.BooleanField(default=True, verbose_name='\u0412 \u043d\u0430\u043b\u0438\u0447\u0438\u0438')),
                ('holder', models.CharField(blank=True, max_length=255, verbose_name='\u0423 \u043a\u043e\u0433\u043e \u043d\u0430 \u0440\u0443\u043a\u0430\u0445')),
                ('receiving_date', models.DateField(blank=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u044f')),
                ('return_date', models.DateField(blank=True, verbose_name='\u0414\u0430\u0442\u0430 \u0432\u043e\u0437\u0432\u0440\u0430\u0442\u0430')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legoteka.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u0435\u0434\u043c\u0435\u0442 \u043b\u0435\u0433\u043e\u0442\u0435\u043a\u0438',
                'verbose_name_plural': '\u041f\u0440\u0435\u0434\u043c\u0435\u0442\u044b \u043b\u0435\u0433\u043e\u0442\u0435\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='LegotekaItemOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u0424\u0418\u041e')),
                ('contacts', models.CharField(max_length=255, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d \u0438\u043b\u0438 email')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='\u041f\u0440\u0438\u043c\u0435\u0447\u0430\u043d\u0438\u0435')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legoteka.LegotekaItem', verbose_name='\u041f\u0440\u0435\u0434\u043c\u0435\u0442')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u044f\u0432\u043a\u0430 \u043d\u0430 \u043f\u0440\u0435\u0434\u043c\u0435\u0442 \u043b\u0435\u0433\u043e\u0442\u0435\u043a\u0438',
                'verbose_name_plural': '\u0417\u0430\u044f\u0432\u043a\u0438 \u043d\u0430 \u043f\u0440\u0435\u0434\u043c\u0435\u0442\u044b \u043b\u0435\u0433\u043e\u0442\u0435\u043a\u0438',
            },
        ),
    ]
