# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legoteka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legotekaitem',
            name='photo',
            field=models.ImageField(default='', upload_to='legoteka/', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f'),
            preserve_default=False,
        ),
    ]
