# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legoteka', '0002_legotekaitem_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legotekaitem',
            name='receiving_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='legotekaitem',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0432\u043e\u0437\u0432\u0440\u0430\u0442\u0430'),
        ),
    ]
