# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legoteka', '0003_auto_20160327_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legotekaitemorder',
            name='note',
            field=models.TextField(blank=True, verbose_name='\u041f\u0440\u0438\u043c\u0435\u0447\u0430\u043d\u0438\u0435'),
        ),
    ]
