# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aidtype',
            options={'verbose_name': '\u0442\u0438\u043f \u0433\u0443\u043c\u0430\u043d\u0438\u0442\u0430\u0440\u043d\u043e\u0439 \u043f\u043e\u043c\u043e\u0449\u044c', 'verbose_name_plural': '\u0442\u0438\u043f\u044b \u0433\u0443\u043c\u0430\u043d\u0438\u0442\u0430\u0440\u043d\u043e\u0439 \u043f\u043e\u043c\u043e\u0449\u0438'},
        ),
        migrations.AlterModelOptions(
            name='givingaid',
            options={'verbose_name': '\u0437\u0430\u044f\u0432\u043a\u0430 \u043d\u0430 \u043e\u043a\u0430\u0437\u0430\u043d\u0438\u0435 \u0433\u0443\u043c \u043f\u043e\u043c\u043e\u0449\u0438', 'verbose_name_plural': '\u0437\u0430\u044f\u0432\u043a\u0438 \u043d\u0430 \u043e\u043a\u0430\u0437\u0430\u043d\u0438\u0435 \u0433\u0443\u043c \u043f\u043e\u043c\u043e\u0449\u0438'},
        ),
    ]
