# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0002_auto_20160326_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidtype',
            name='title',
            field=models.CharField(max_length=60, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='humanitarianaid',
            name='type',
            field=models.CharField(choices=[('1', '\u0414\u043b\u044f \u0440\u043e\u0434\u0438\u0442\u0435\u043b\u0435\u0439'), ('2', '\u0414\u043b\u044f \u043f\u043e\u0442\u0435\u043d\u0446\u0438\u0430\u043b\u044c\u043d\u044b\u0445 \u0441\u043f\u043e\u043d\u0441\u043e\u0440\u043e\u0432: \u0414\u0435\u0442\u044f\u043c'), ('3', '\u0414\u043b\u044f \u043f\u043e\u0442\u0435\u043d\u0446\u0438\u0430\u043b\u044c\u043d\u044b\u0445 \u0441\u043f\u043e\u043d\u0441\u043e\u0440\u043e\u0432: \u0426\u0435\u043d\u0442\u0440\u0443')], default=1, max_length=1, verbose_name='\u0422\u0438\u043f \u0433\u0443\u043c\u0430\u043d\u0438\u0442\u0430\u0440\u043d\u043e\u0439 \u043f\u043e\u043c\u043e\u0449\u0438'),
        ),
    ]
