# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0003_auto_20160326_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanitarianAidForKid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0433\u0443\u043c\u0430\u043d\u0438\u0442\u0430\u0440\u043d\u0430\u044f \u043f\u043e\u043c\u043e\u0449\u044c \u0440\u043e\u0434\u0438\u0442\u0435\u043b\u044f\u043c',
                'verbose_name_plural': '\u0433\u0443\u043c\u0430\u043d\u0438\u0442\u0430\u0440\u043d\u0430\u044f \u043f\u043e\u043c\u043e\u0449\u044c \u0440\u043e\u0434\u0438\u0442\u0435\u043b\u044f\u043c',
            },
        ),
        migrations.CreateModel(
            name='HumanitarianAidForSponsors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('type', models.CharField(choices=[('1', '\u0414\u0435\u0442\u044f\u043c'), ('2', '\u0426\u0435\u043d\u0442\u0440\u0443')], default=1, max_length=1, verbose_name='\u041a\u043e\u043c\u0443?')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0434\u043b\u044f \u043f\u043e\u0442\u0435\u043d\u0446\u0438\u0430\u043b\u044c\u043d\u044b\u0445 \u0441\u043f\u043e\u043d\u0441\u043e\u0440\u043e\u0432',
                'verbose_name_plural': '\u0434\u043b\u044f \u043f\u043e\u0442\u0435\u043d\u0446\u0438\u0430\u043b\u044c\u043d\u044b\u0445 \u0441\u043f\u043e\u043d\u0441\u043e\u0440\u043e\u0432',
            },
        ),
        migrations.AlterField(
            model_name='aidrequest',
            name='aid_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aid.HumanitarianAidForKid', verbose_name='\u0413\u0443\u043c\u0430\u043d\u0438\u0442\u0430\u0440\u043d\u0430\u044f \u043f\u043e\u043c\u043e\u0449\u044c'),
        ),
        migrations.DeleteModel(
            name='HumanitarianAid',
        ),
    ]
