# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('description', redactor.fields.RedactorField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0438 \u0443\u0441\u043b\u043e\u0432\u0438\u044f')),
                ('payment_center', models.CharField(max_length=255, verbose_name='\u041e\u043f\u043b\u0430\u0442\u0430 \u0441\u043e \u0441\u0442\u043e\u0440\u043e\u043d\u044b \u0446\u0435\u043d\u0442\u0440\u0430')),
                ('payment_sponsor', models.CharField(max_length=255, verbose_name='\u041e\u043f\u043b\u0430\u0442\u0430 \u043e\u0442 \u0441\u043f\u043e\u043d\u0441\u043e\u0440\u0430')),
                ('sponsor', models.CharField(max_length=255, verbose_name='\u0421\u043f\u043e\u043d\u0441\u043e\u0440')),
            ],
            options={
                'verbose_name': '\u0421\u043e\u0431\u044b\u0442\u0438\u0435 \u0441\u043e\u043e\u043f\u043b\u0430\u0447\u0435\u043d\u043d\u043e\u0435 \u0441\u043f\u043e\u043d\u0441\u043e\u0440\u043e\u043c',
                'verbose_name_plural': '\u0421\u043e\u0431\u044b\u0442\u0438\u044f \u0441\u043e\u043e\u043f\u043b\u0430\u0447\u0435\u043d\u043d\u044b\u0435 \u0441\u043f\u043e\u043d\u0441\u043e\u0440\u0430\u043c\u0438',
            },
        ),
    ]
