# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 08:18
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_financialeventparticipants'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialevent',
            name='date',
            field=models.DateTimeField(default=timezone.now(), verbose_name='\u0412\u0440\u0435\u043c\u044f \u043f\u0440\u043e\u0432\u0435\u0434\u0435\u043d\u0438\u044f'),
            preserve_default=False,
        ),
    ]
