# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('url', models.CharField(max_length=255, verbose_name='Url')),
                ('content', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
            ],
            options={
                'verbose_name': 'c\u0442\u0440\u0430\u043d\u0438\u0446\u0430',
                'verbose_name_plural': 'c\u0442\u0440\u0430\u043d\u0438\u0446\u044b',
            },
        ),
    ]
